language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle

before_script:
  - chmod +x gradlew --console=plain

script: ./gradlew check

deploy:
  provider: script
  script: ./gradlew bintrayUpload --console=plain
  skip_cleanup: true
  on:
    branch: master
    tags: true